# Generated by Django 3.0.3 on 2020-04-12 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HN', models.CharField(max_length=9)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='patient_mpi',
            fields=[
                ('mpi_id', models.AutoField(primary_key=True, serialize=False)),
                ('mpi_date', models.DateTimeField(auto_now_add=True)),
                ('LAD_4dmspect', models.DecimalField(decimal_places=2, max_digits=20)),
                ('LAD_wallthick', models.DecimalField(decimal_places=2, max_digits=20)),
                ('LAD_wallmotion', models.DecimalField(decimal_places=2, max_digits=20)),
                ('LAD_CAG', models.CharField(max_length=1)),
                ('LCX_4dmspect', models.DecimalField(decimal_places=2, max_digits=20)),
                ('LCX_wallthick', models.DecimalField(decimal_places=2, max_digits=20)),
                ('LCX_wallmotion', models.DecimalField(decimal_places=2, max_digits=20)),
                ('LCX_CAG', models.CharField(max_length=1)),
                ('RCA_4dmspect', models.DecimalField(decimal_places=2, max_digits=20)),
                ('RCA_wallthick', models.DecimalField(decimal_places=2, max_digits=20)),
                ('RCA_wallmotion', models.DecimalField(decimal_places=2, max_digits=20)),
                ('RCA_CAG', models.CharField(max_length=1)),
                ('LVEF', models.IntegerField()),
                ('HN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patients')),
            ],
        ),
        migrations.CreateModel(
            name='patient_characteristic',
            fields=[
                ('cha_id', models.AutoField(primary_key=True, serialize=False)),
                ('cha_date', models.DateTimeField(auto_now_add=True)),
                ('bmi', models.DecimalField(decimal_places=2, max_digits=20)),
                ('dm', models.CharField(max_length=1)),
                ('ht', models.CharField(max_length=1)),
                ('dlp', models.CharField(max_length=1)),
                ('ckd', models.CharField(max_length=1)),
                ('HN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patients')),
            ],
        ),
    ]
