# Generated by Django 3.0.3 on 2020-04-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='age',
        ),
        migrations.AddField(
            model_name='patient_characteristic',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
